version: '3.7'

services:
  api01: # API - Instância 01
    build:
      context: .
      dockerfile: api/.docker/php/Dockerfile
    restart: on-failure
    hostname: api01
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - db
    user: 1000:1000
    volumes:
      - "./api:/usr/src/api"
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.15'
    #      memory: '0.4GB'

  api02: # API - Instância 02
    build:
      context: .
      dockerfile: api/.docker/php/Dockerfile
    restart: on-failure
    hostname: api02
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    depends_on:
      - db
    user: 1000:1000
    volumes:
      - "./api:/usr/src/api"


  nginx: # Load Balancer
    image: nginx:1.15.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:80"
    network_mode: "host" 
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

  db: # Banco de dados
    image: mysql:8.0
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'

networks:
  default:
    driver: bridge
    name: rinha